name: weather_app
description: Flutter Weather app with Firebase Auth and Firestore.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core + Auth + Firestore
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.14.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # HTTP package for API calls
  http: ^0.13.6

  # Provider for state management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.0

  # Add flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # flutter_launcher_icons config
  assets:
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
